version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    ports:
      - "19092:19092" # "宿主机:容器"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka:9092,PLAINTEXT://localhost:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  redis-cluster:
    image: 'redis:6.0-alpine'
    container_name: redis-cluster
    command: redis-cli --cluster create ${EXTERNAL_IP}:7001 ${EXTERNAL_IP}:7002 ${EXTERNAL_IP}:7003 ${EXTERNAL_IP}:7004 ${EXTERNAL_IP}:7005 ${EXTERNAL_IP}:7006 --cluster-replicas 1 --cluster-yes
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
  redis-node-1:
    image: redis:6.0-alpine
    container_name: redis-node-1
    command: redis-server --port 7001 --appendonly yes --protected-mode no --cluster-enabled yes --cluster-announce-ip ${EXTERNAL_IP} --cluster-announce-port 7001 --cluster-announce-bus-port 17001
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '7001:7001'
      - '17001:17001'
  redis-node-2:
    image: redis:6.0-alpine
    container_name: redis-node-2
    command: redis-server --port 7002 --appendonly yes --protected-mode no --cluster-enabled yes --cluster-announce-ip ${EXTERNAL_IP} --cluster-announce-port 7002 --cluster-announce-bus-port 17002
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '7002:7002'
      - '17002:17002'
  redis-node-3:
    image: redis:6.0-alpine
    container_name: redis-node-3
    command: redis-server --port 7003 --appendonly yes --protected-mode no --cluster-enabled yes --cluster-announce-ip ${EXTERNAL_IP} --cluster-announce-port 7003 --cluster-announce-bus-port 17003
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '7003:7003'
      - '17003:17003'
  redis-node-4:
    image: redis:6.0-alpine
    container_name: redis-node-4
    command: redis-server --port 7004 --appendonly yes --protected-mode no --cluster-enabled yes --cluster-announce-ip ${EXTERNAL_IP} --cluster-announce-port 7004 --cluster-announce-bus-port 17004
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '7004:7004'
      - '17004:17004'
  redis-node-5:
    image: redis:6.0-alpine
    container_name: redis-node-5
    command: redis-server --port 7005 --appendonly yes --protected-mode no --cluster-enabled yes --cluster-announce-ip ${EXTERNAL_IP} --cluster-announce-port 7005 --cluster-announce-bus-port 17005
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '7005:7005'
      - '17005:17005'
  redis-node-6:
    image: redis:6.0-alpine
    container_name: redis-node-6
    command: redis-server --port 7006 --appendonly yes --protected-mode no --cluster-enabled yes --cluster-announce-ip ${EXTERNAL_IP} --cluster-announce-port 7006 --cluster-announce-bus-port 17006
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '7006:7006'
      - '17006:17006'
